### ISSUE TITLE
Example not working with tilelive 5.7.1

### ISSUE THREAD

**Issue by nicomgd** [oscarfonts/tilelive-tms#1]
Hi,

I have to patch [`tilelive-tms.js`](https://github.com/oscarfonts/tilelive-tms/blob/master/lib/tilelive-tms.js#L9) at line 9 to make the example work.

I had to change `this.uri = uri.href;` to `this.uri = decodeURIComponent(uri.href);`.

I suppose this is related to a change in recent `tilelive` versions (I used version `5.7.1`).

**Comment by oscarfonts** [comment]
Just tested with the latest versions from npm (request@2.64.0, tilelive@5.9.0, mbtiles@0.8.0 and tilelive-tms@0.1.0) on Ubuntu 15.04 and it worked.

Tried your change and it works too, but it makes more sense to pass the URLs around correctly encoded, so I'm not in favor of incorporating it.

BTW, I changed the README and example.js to use a public GeoServer instance, so it can be run straightforward.

Please test again with the new example URL and the indicated package versions. Which OS are you using? How about the tilelive-copy method explained in README? Does it work?

Thanks for the feedback!

**Comment by nicomgd** [comment]
Just tried again (install log follows) : same problem, under Windows & node 0.12.5.

The example command fails, as before :

```
C:\temp\test>node_modules\.bin\tilelive-copy tms:http://demo.opengeo.org/geoserver/gwc/service/tms/1.0.0/ne%3ANE1_HR_LC_SR_W_DR@
EPSG%3A900913@jpeg/{z}/{x}/{y}.jpg mbtiles://./naturalearth.mbtiles --bounds=-180,-90,180,90 --minzoom=0 --maxzoom=4
C:\temp\test\node_modules\tilelive\bin\tilelive-copy:96
        if (err) throw err;
                       ^
Error: TMS URL template must contain {z}, {x} and {y} placeholders.
    at new TmsSource (C:\temp\test\node_modules\tilelive-tms\lib\tilelive-tms.js:12:18)
    at Object.tilelive.load (C:\temp\test\node_modules\tilelive\lib\tilelive.js:95:27)
    at C:\temp\test\node_modules\tilelive\lib\tilelive.js:333:18
    at pop (C:\temp\test\node_modules\queue-async\queue.js:24:14)
    at Object.q.defer (C:\temp\test\node_modules\queue-async\queue.js:55:11)
    at Object.tilelive.copy (C:\temp\test\node_modules\tilelive\lib\tilelive.js:331:36)
    at copy (C:\temp\test\node_modules\tilelive\bin\tilelive-copy:95:14)
    at Object.<anonymous> (C:\temp\test\node_modules\tilelive\bin\tilelive-copy:70:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Install log

```
C:\temp\test>npm install request tilelive mbtiles tilelive-tms
npm WARN engine tilelive@5.9.0: wanted: {"node":">= 0.10.0 < 0.11.0"} (current: {"node":"0.12.5","npm":"3.3.3"})
npm WARN engine tilelive@5.9.0: wanted: {"node":">= 0.10.0 < 0.11.0"} (current: {"node":"0.12.5","npm":"3.3.3"})
npm WARN engine tiletype@0.1.0: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.5","npm":"3.3.3"})

> sqlite3@3.0.10 install C:\temp\test\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "C:\temp\test\node_modules\sqlite3\lib\binding\node-v14-win32-x64\node_sqlite3.node" is installed via remote
C:\temp\test
├─┬ mbtiles@0.8.0
│ ├── sphericalmercator@1.0.4
│ ├─┬ sqlite3@3.0.10
│ │ ├── nan@1.8.4
│ │ └─┬ node-pre-gyp@0.6.9
│ │   ├─┬ npmlog@1.2.1
│ │   │ └─┬ are-we-there-yet@1.0.4
│ │   │   └─┬ readable-stream@1.1.13
│ │   │     ├── core-util-is@1.0.1
│ │   │     ├── inherits@2.0.1
│ │   │     ├── isarray@0.0.1
│ │   │     └── string_decoder@0.10.31
│ │   ├─┬ request@2.60.0
│ │   │ ├── aws-sign2@0.5.0
│ │   │ ├─┬ bl@1.0.0
│ │   │ │ └─┬ readable-stream@2.0.2
│ │   │ │   ├── core-util-is@1.0.1
│ │   │ │   ├── inherits@2.0.1
│ │   │ │   ├── isarray@0.0.1
│ │   │ │   ├── string_decoder@0.10.31
│ │   │ │   └── util-deprecate@1.0.1
│ │   │ ├── caseless@0.11.0
│ │   │ ├─┬ combined-stream@1.0.5
│ │   │ │ └── delayed-stream@1.0.0
│ │   │ ├── extend@3.0.0
│ │   │ ├── forever-agent@0.6.1
│ │   │ ├─┬ har-validator@1.8.0
│ │   │ │ ├─┬ chalk@1.1.0
│ │   │ │ │ ├── ansi-styles@2.1.0
│ │   │ │ │ ├── escape-string-regexp@1.0.3
│ │   │ │ │ ├─┬ has-ansi@2.0.0
│ │   │ │ │ │ └── ansi-regex@2.0.0
│ │   │ │ │ ├─┬ strip-ansi@3.0.0
│ │   │ │ │ │ └── ansi-regex@2.0.0
│ │   │ │ │ └── supports-color@2.0.0
│ │   │ │ ├─┬ commander@2.8.1
│ │   │ │ │ └── graceful-readlink@1.0.1
│ │   │ │ └─┬ is-my-json-valid@2.12.1
│ │   │ │   ├── generate-function@2.0.0
│ │   │ │   ├─┬ generate-object-property@1.2.0
│ │   │ │   │ └── is-property@1.0.2
│ │   │ │   └── xtend@4.0.0
│ │   │ ├─┬ hawk@3.1.0
│ │   │ │ └── sntp@1.0.9
│ │   │ ├─┬ http-signature@0.11.0
│ │   │ │ ├── asn1@0.1.11
│ │   │ │ ├── assert-plus@0.1.5
│ │   │ │ └── ctype@0.5.3
│ │   │ ├── isstream@0.1.2
│ │   │ ├── json-stringify-safe@5.0.1
│ │   │ ├── node-uuid@1.4.3
│ │   │ ├── oauth-sign@0.8.0
│ │   │ ├── stringstream@0.0.4
│ │   │ └── tunnel-agent@0.4.1
│ │   ├─┬ rimraf@2.4.2
│ │   │ └─┬ glob@5.0.14
│ │   │   └── inherits@2.0.1
│ │   ├─┬ tar@2.1.1
│ │   │ └── inherits@2.0.1
│ │   └─┬ tar-pack@2.0.0
│ │     ├─┬ fstream@0.1.31
│ │     │ └── inherits@2.0.1
│ │     ├─┬ fstream-ignore@0.0.7
│ │     │ └── inherits@2.0.1
│ │     ├─┬ readable-stream@1.0.33
│ │     │ ├── core-util-is@1.0.1
│ │     │ ├── inherits@2.0.1
│ │     │ ├── isarray@0.0.1
│ │     │ └── string_decoder@0.10.31
│ │     └─┬ tar@0.1.20
│ │       └── inherits@2.0.1
│ └── tiletype@0.1.0
├─┬ request@2.64.0
│ ├── aws-sign2@0.5.0
│ ├─┬ bl@1.0.0
│ │ └─┬ readable-stream@2.0.2
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   ├── process-nextick-args@1.0.3
│ │   ├── string_decoder@0.10.31
│ │   └── util-deprecate@1.0.1
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.0
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@1.0.0-rc3
│ │ └── async@1.4.2
│ ├─┬ har-validator@1.8.0
│ │ ├── bluebird@2.10.2
│ │ ├─┬ chalk@1.1.1
│ │ │ ├── ansi-styles@2.1.0
│ │ │ ├── escape-string-regexp@1.0.3
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ commander@2.8.1
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ is-my-json-valid@2.12.2
│ │   ├── generate-function@2.0.0
│ │   ├─┬ generate-object-property@1.2.0
│ │   │ └── is-property@1.0.2
│ │   ├── jsonpointer@2.0.0
│ │   └── xtend@4.0.0
│ ├─┬ hawk@3.1.0
│ │ ├── boom@2.9.0
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@0.11.0
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.5
│ │ └── ctype@0.5.3
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.7
│ │ └── mime-db@1.19.0
│ ├── node-uuid@1.4.3
│ ├── oauth-sign@0.8.0
│ ├── qs@5.1.0
│ ├── stringstream@0.0.4
│ ├── tough-cookie@2.1.0
│ └── tunnel-agent@0.4.1
├─┬ tilelive@5.9.0
│ ├── minimist@0.2.0
│ ├─┬ progress-stream@0.5.0
│ │ ├── single-line-log@0.3.1
│ │ ├── speedometer@0.1.4
│ │ └─┬ through2@0.2.3
│ │   ├── readable-stream@1.1.13
│ │   └─┬ xtend@2.1.2
│ │     └── object-keys@0.4.0
│ └── queue-async@1.0.7
└── tilelive-tms@0.1.0

npm WARN ENOENT ENOENT, open 'C:\temp\test\package.json'
npm WARN EPACKAGEJSON C:\temp\test No description
npm WARN EPACKAGEJSON C:\temp\test No repository field.
npm WARN EPACKAGEJSON C:\temp\test No README data
npm WARN EPACKAGEJSON C:\temp\test No license field.
```

**Comment by oscarfonts** [comment]
Ok, the problem actually was with node version 0.12.x (I'm using 0.10.x), not Windows.
Applied your patch and published as tilelive-tms v.0.1.1.
Please run an npm update and try again.

Thank you!
Also thanks to @sergioedo for testing.
